apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rathena.fullname" . }}-configmap
data:
  char_conf.txt: |-
    server_name: {{ template "rathena.fullname" . }}
    wisp_server_name: {{ template "rathena.fullname" . }}
    login_ip: 104.238.129.213
    login_port: 6900 
    char_ip: 104.238.129.213
    char_port: 6121
    //bind_ip: 104.238.129.213

  login_conf.txt: |-
    new_account: yes
    login_port: 6900
    //bind_ip: 104.238.129.213

  map_conf.txt: |-
    char_ip: 104.238.129.213
    char_port: 6121
    map_ip: 104.238.129.213
    map_port: 5121
    //bind_ip: 104.238.129.213

  inter_conf.txt: |-
    // MySQL Login server
    login_server_ip: mariadb.rathena.svc.cluster.local
    login_server_port: 3306
    login_server_id: {{ .Values.mariadb.auth.username }}
    login_server_pw: {{ .Values.mariadb.auth.password }}
    login_server_db: {{ .Values.mariadb.auth.database }}

    ipban_db_ip: mariadb.rathena.svc.cluster.local
    ipban_db_port: 3306
    ipban_db_id: {{ .Values.mariadb.auth.username }}
    ipban_db_pw: {{ .Values.mariadb.auth.password }}
    ipban_db_db: {{ .Values.mariadb.auth.database }}

    // MySQL Character server
    char_server_ip: mariadb.rathena.svc.cluster.local
    char_server_port: 3306
    char_server_id: {{ .Values.mariadb.auth.username }}
    char_server_pw: {{ .Values.mariadb.auth.password }}
    char_server_db: {{ .Values.mariadb.auth.database }}

    // MySQL Map Server
    map_server_ip: mariadb.rathena.svc.cluster.local
    map_server_port: 3306
    map_server_id: {{ .Values.mariadb.auth.username }}
    map_server_pw: {{ .Values.mariadb.auth.password }}
    map_server_db: {{ .Values.mariadb.auth.database }}

    // MySQL Log Database
    log_db_ip: mariadb.rathena.svc.cluster.local
    log_db_port: 3306
    log_db_id: {{ .Values.mariadb.auth.username }}
    log_db_pw: {{ .Values.mariadb.auth.password }}
    log_db_db: {{ .Values.mariadb.auth.database }}

{{ range $path, $_ :=  .Files.Glob  "config/**" }}
{{ $path | trimPrefix "config/" | nindent 2 }}: |-
{{ $.Files.Get $path | nindent 4 }}
{{ end }}
