apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rathena.fullname" . }}-initdb-configmap
data:
{{ range $path, $_ :=  .Files.Glob  "database/**" }}
{{ $path | trimPrefix "database/" | nindent 2 }}: |-
{{ $.Files.Get $path | nindent 4 }}
{{ end }}