---
apiVersion: v1
kind: Service
metadata:
  name: game
  labels:
    app: {{ template "rathena.name" $ }}
    chart: {{ template "rathena.chart" $ }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $val := .Values.containers }}
    - name: {{ .service.name }}
      port: {{ .service.port }}
      protocol: {{ .service.protocol }}
      targetPort: {{ .service.name }}
    {{- end }}
  selector:
    app: {{ template "rathena.name" $ }}
    release: {{ .Release.Name }}

{{- range $key, $val := .Values.containers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  labels:
    app: {{ template "rathena.name" $ }}
    chart: {{ template "rathena.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - name: {{ .service.name }}
      port: {{ .service.port }}
      protocol: {{ .service.protocol }}
      targetPort: {{ .service.name }}
  selector:
    app: {{ template "rathena.name" $ }}
    release: {{ $.Release.Name }}
{{- end }}