name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v3
    - name: update deps
      run: apk update
    - name: install deps
      run: apk add --no-cache git cmake make gcc g++ gdb zlib-dev mariadb-dev ca-certificates linux-headers bash
    - name: configure
      run: ./configure --enable-packetver=20151104
    - name: make
      run: make clean server
    - name: ls files
      run: ls -la *-server
    
